{% set name = "primecountpy" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/primecountpy-{{ version }}.tar.gz
  sha256: 888706ab65cc089fb983de4639360dddc728baa4d9877a7ad8b116f645650b39

build:
  skip: true  # [py<311]
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - cysignals
    - cython
    - pip
    - setuptools
    - primecount
    - python
  run:
    - cysignals
    - python

test:
  imports:
    - primecountpy

about:
  home: https://github.com/dimpase/primecountpy
  summary: Cython interface for C++ primecount library
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saraedum
    - isuruf
