{% set name = "primecountpy" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/primecountpy-{{ version }}.tar.gz
  sha256: c8561817c0be86eeffc41b97b6ef617d795f72cf3de59d9234d1c83d7e424030

build:
  skip: true  # [py<37]
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - cysignals
    - cython
    - pip
    - setuptools
    - primecount
    - python
  run:
    - cysignals
    - python

test:
  imports:
    - primecountpy

about:
  home: https://github.com/dimpase/primecountpy
  summary: Cython interface for C++ primecount library
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saraedum
    - isuruf
