{% set name = "primecountpy" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/primecountpy-{{ version }}.tar.gz
  sha256: 888706ab65cc089fb983de4639360dddc728baa4d9877a7ad8b116f645650b39
  patches:
    - fix-prime-pi-128-cast.patch

build:
  skip: true  # [py<312]
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation -Csetup-args=--wrap-mode=nofallback  # [not win]
  script: copy %LIBRARY_LIB%\primesieve.dll.lib %LIBRARY_LIB%\primesieve.lib && {{ PYTHON }} -m pip install . -vv --no-build-isolation -Csetup-args=--wrap-mode=nofallback  # [win]
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython
    - cysignals
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - meson
    - ninja
    - pkg-config
  host:
    - cysignals
    - cython
    - meson-python
    - pip
    - primecount >8.0
    - primesieve  # [win]
    - python
  run:
    - cysignals
    - python

test:
  imports:
    - primecountpy
  commands:
    - python -c "from primecountpy.primecount import prime_pi; assert prime_pi(1000) == 168"

about:
  home: https://github.com/dimpase/primecountpy
  summary: Cython interface for C++ primecount library
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - saraedum
    - isuruf
